# Generated by Django 4.0.6 on 2022-10-21 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_assignment_submission_assignmentusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='auth_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
